version: "3.8"

services:
  auth-service:
    build: ../Authentication-Service
    ports:
      - "5001:5001"
    networks:
      - backend

  logic-service:
    build: ../Business-Logic-Service
    ports:
      - "5002:5002"
    networks:
      - backend

  db-service:
    build: ../Database-Interaction-Service
    ports:
      - "5003:5003"
    networks:
      - backend

networks:
  backend:
    driver: bridge
