version: "3.8"

services:
  auth-service:
    build: ../Authentication-Service
    ports:
      - "5001:5001"
    networks:
      - backend

  logic-service:
    build: ../Business-Logic-Service
    ports:
      - "5002:5002"
    networks:
      - backend

  db-service:
    build: ../Database-Interaction-Service
    ports:
      - "5003:5003"
    networks:
      - backend

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bookmeup
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - backend

  kong:
    image: kong:3.4
    container_name: kong
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_LOG_LEVEL: debug
    volumes:
      - ./infrastructure/kong.yml:/etc/kong/kong.yml
    ports:
      - "8000:8000"   # public access
      - "8001:8001"   # Kong admin API (optional)
    networks:
      - backend

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "9000:9000"
    networks:
      - backend

volumes:
  pgdata:
  portainer_data:

networks:
  backend:
    driver: bridge
