version: "3.9"

services:
  auth-service:
    image: alexnv67/auth-service
    ports:
      - "5001:5001"
    networks:
      - backend

  logic-service:
    image: alexnv67/logic-service
    ports:
      - "5002:5002"
    networks:
      - backend

  db-service:
    image: alexnv67/db-service
    ports:
      - "5003:5003"
    networks:
      - backend

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bookmeup
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - backend

  kong:
    image: kong:3.4
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yml
    volumes:
      - ./infrastructure/kong.yml:/etc/kong/kong.yml
    ports:
      - "8000:8000"
      - "8001:8001"
    networks:
      - backend

  portainer:
    image: portainer/portainer-ce
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "9000:9000"
    networks:
      - backend

volumes:
  postgres_data:
  portainer_data:

networks:
  backend:
    driver: overlay
