global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:5001']
  - job_name: 'logic-service'
    static_configs:
      - targets: ['logic-service:5002']
  - job_name: 'db-service'
    static_configs:
      - targets: ['db-service:5003']